# Generated by Django 5.0.6 on 2026-05-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"is_service": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="products.product",
            ),
        ),
    ]
