# Generated by Django 5.0.6 on 2026-05-21 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('order_completed', 'Order Completed'), ('stock_updated', 'Stock Updated'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vendors.vendor')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'permissions': [('cannot_update_auditlog', 'Cannot update audit log entries')],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='audit_logs_vendor__d94016_idx')],
            },
        ),
    ]
